[package]
name = "chip8"
version = "0.0.1"
authors = ["wickus.martin <wickus.martin@gmail.com>"]

[[bin]]
name = "chip8"
path = "src/main.rs"

[dependencies]
sdl2 = "*"
rand = "*"
getopts = "*"
time = "*"
